### ISSUE TITLE
Exception thrown on unknown item in UserInformation

### ISSUE THREAD

**Issue by lamyj** [lamyj/odil#12]
When reading an unknown item in UserInformation, an exception is [thrown](https://github.com/lamyj/odil/blob/e315100/src/odil/pdu/UserInformation.cpp#L99).

Short-term fix: skip unknown items, assuming the structure is always the same (item-type, reserved, item-length), and issue a warning.

Long-term fix: as above, plus #9, #10, #11.

@fredchamp, @edouard-mangel: is this the one we talked about?

**Comment by FredChamp** [comment]
Yes, is exactly the issue we encountred.
