### ISSUE TITLE
Is the dependency to DCMTK still necessary ?

### ISSUE THREAD

**Issue by cguebert** [lamyj/odil#18]
While trying to build the tests on windows, I came across a difficulty for dcmtk/ElementAccessor.
Indeed, it is near impossible to export in a dll a static member of a template class (element_get & element_set).

I could rewrite the class to make it possible, but I have to ask if it is really necessary.
By doing a quick search through the code base, it seems the odil/dcmtk classes are not used anymore.
If so, can we remove the dependency to DCMTK from odil ?
If not, where is DCMTK still used ?

**Comment by lamyj** [comment]
For the build itself, DCMTK is not mandatory, provided the `src/dcmtk` subdirectory is excluded from the compilation (i.e. no DCMTK converter): that's totally fine for me. For the tests, the situation is a bit more convoluted: the read and write tests consider DCMTK write and read as ground truth, and a lot of Linux distributions I'm still supporting do not include the `getscu` executable (Ubuntu <= 14.04, Debian <= 8), used in the GetSCP test. 

I think that skipping those tests is not a good idea, so is it OK for you to have the tests depending on DCMTK and a conditional dependence for the build process?

**Comment by cguebert** [comment]
That would be a good first step.
Could we move the dcmtk file to a new library if they are only used for the tests then ?
