### ISSUE TITLE
make uninstall

### ISSUE THREAD

**Issue by ferdymercury** [lamyj/odil#79]
Just a minor feature suggestion. Having a make uninstall command could be helpful, see:

https://gitlab.kitware.com/cmake/community/-/wikis/FAQ#can-i-do-make-uninstall-with-cmake

**Comment by lamyj** [comment]
Why on earth would you want to uninstall Odil !?! Joke aside, done in 5ab26b9, following Kitware's advice to the letter. Note that it will leave behind empty directories (it does not seem possible to know whether CMake created them or not) and files generated after the installation (e.g. bytecode Python files, same remark about creation).

**Comment by ferdymercury** [comment]
hahah indeed, no one would want to such a thing.

But Odil is even cooler now that he can ;)

Thanks for the amazing support!
