### ISSUE TITLE
LGTM recommendation: Large object passed by value

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [lamyj/odil#89]
This parameter of type [`Selector`](https://github.com/lamyj/odil/blob/dc8d063d8ecf1fa787a3e2de7f5b9a9574fa1105/src/odil/webservices/Selector.h#L26) is 128 bytes - consider passing a const pointer/reference instead.
https://lgtm.com/projects/g/lamyj/odil/snapshot/5a2247ba9613a54e493954b70019dc19e5f6339d/files/wrappers/python/webservices/STOWRSRequest.cpp?sort=name&dir=ASC&mode=heatmap#x30cadaa14f031ec9:1

**Comment by DimitriPapadopoulos** [comment]
How would you feel fixing this by passing the "large object" by reference?

**Comment by lamyj** [comment]
A reference was definitely missing, thanks.
